Create doc/guide for multiple domains hosting with Beacon
BeaconCMS/beacon pull request #393
Opened 2024-01-12 21:34 UTC by alexandrexaviersm

Issue: https://github.com/BeaconCMS/beacon/issues/95

2024-01-19 18:16 UTC, leandrocp requested changes
Nice. Just a few comments to make it a bit more clear.

2024-01-19 18:16 UTC, leandrocp commented on guides/deployment/multiple_domains_hosting.md
> +  scope "/admin" do
```suggestion
  # serve the admin interface at the prefix /admin on the root domain
  scope "/admin" do
```

2024-01-26 04:09 UTC, alexandrexaviersm commented on guides/deployment/multiple_domains_hosting.md
> +    beacon_site "/blog", site: :blog
I took it from here: https://github.com/BeaconCMS/beacon_demo/blob/main/lib/beacon_demo_web/router.ex#L23

so now I'm confused what the correct way would be 🤔

2024-01-26 15:30 UTC, leandrocp approved these changes

2024-01-26 15:30 UTC, merged