Layouts: Sorting and Pagination
BeaconCMS/beacon pull request #445
Opened 2024-04-05 17:44 UTC by ChristianTovar

2024-04-26 17:20 UTC, APB9785 approved these changes
Nice! 🥳

2024-04-29 18:44 UTC, leandrocp requested changes

2024-04-29 18:44 UTC, leandrocp commented on lib/beacon/content.ex
> +    * `:query` - search assets by file name. Defaults to `nil`, doesn't filter query.
```suggestion
    * `:query` - search layouts by title. Defaults to `nil`, doesn't filter query.
```

2024-04-29 18:44 UTC, leandrocp approved these changes

2024-04-29 18:56 UTC, leandrocp commented
🎉

2024-04-29 18:57 UTC, merged