Add adjusts for the Component Attribute context
BeaconCMS/beacon pull request #535
Opened 2024-06-27 06:53 UTC by alexandrexaviersm

2024-06-27 06:57 UTC, alexandrexaviersm commented on lib/beacon/content.ex
> +    # Do I need to do this for component_attr?
@leandrocp

2024-06-27 07:02 UTC, alexandrexaviersm commented on priv/repo/migrations/20240621085408_add_struct_name_to_beacon_component_attrs.exs
> +      add :struct_name, :string
Having this field really helped setting up the form in the UI - with this a lot of code was cut 🔪  - also, I think that is more clear to have the field `type` just to save the `component_type` and this field specific to save the **struct name** if the `type` is `struct`

2024-07-10 19:39 UTC, leandrocp requested changes
Looking good. Just a few comments

2024-07-10 19:39 UTC, leandrocp commented on lib/beacon/content.ex
> +  @spec validate_if_value_matches_type(Changeset.t(), String.t(), any(), atom()) :: Changeset.t()
```suggestion
  @doc false
```

You can mark this function semi-private since it's not meant to be called by users, it's only internal.

2024-07-10 19:39 UTC, leandrocp commented on test/support/migrations/20240621085408_add_struct_name_to_beacon_component_attrs.exs
Migrations moved to https://github.com/BeaconCMS/beacon/tree/main/lib/beacon/migrations so you can create v002 with both `alter table` statements.

_The migration in test/support/migrations is used only to execute the migrations in lib/beacon/migrations for the test env._

2024-07-11 01:06 UTC, alexandrexaviersm commented
@leandrocp it looks like `Beacon.Migration` was only running the migration `v001`. So I made some adjusts to it

2024-07-11 01:18 UTC, leandrocp commented
> @leandrocp it looks like `Beacon.Migration` was only running the migration `v001`. So I made some adjusts to it

Sorry I forgot to mention you have to bump the version here https://github.com/BeaconCMS/beacon/blob/ffbfb3d80574e7528d3aa47f5e8eda90813c8d0b/lib/beacon/migration.ex#L6

2024-07-11 01:23 UTC, alexandrexaviersm commented
> > @leandrocp it looks like `Beacon.Migration` was only running the migration `v001`. So I made some adjusts to it
> 
> Sorry I forgot to mention you have to bump the version here
> 
> https://github.com/BeaconCMS/beacon/blob/ffbfb3d80574e7528d3aa47f5e8eda90813c8d0b/lib/beacon/migration.ex#L6

@leandrocp I did bump this version number, but after that it was only running the v002

2024-07-11 01:25 UTC, leandrocp commented
> > > @leandrocp it looks like `Beacon.Migration` was only running the migration `v001`. So I made some adjusts to it
> 
> > 
> 
> > Sorry I forgot to mention you have to bump the version here
> 
> > 
> 
> > https://github.com/BeaconCMS/beacon/blob/ffbfb3d80574e7528d3aa47f5e8eda90813c8d0b/lib/beacon/migration.ex#L6
> 
> 
> 
> @leandrocp I did bump this version number, but after that it was only running the v002

Ok let's use V001 for now.

2024-07-12 16:14 UTC, leandrocp approved these changes

2024-07-12 16:15 UTC, merged